id: persona_01
name: "chrome_windows"
tls_config: chrome_120
http_version: "2"
headers:
  user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36'
  accept: 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8'
  accept-language: 'en-US,en;q=0.9'
  cache-control: 'max-age=0'
  upgrade-insecure-requests: '1'
  sec-ch-ua: '"Chromium";v="125", "Google Chrome";v="125", "Not.A/Brand";v="24"'
  sec-ch-ua-mobile: '?0'
  sec-ch-ua-platform: '"Windows"'
  sec-fetch-dest: 'document'
  sec-fetch-mode: 'navigate'
  sec-fetch-site: 'none'
  sec-fetch-user: '?1'
tcp_parameters:
  ttl: 128
  window_size: 65535
  mss: 1460
