id: persona_04
name: "legacy_browser"
tls_config: randomized
http_version: "1.1"
headers:
  user-agent: 'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1)'
  accept-language: 'en-us'
tcp_parameters:
  ttl: 64
  window_size: 8192
  mss: 536
